import React, { useState, useMemo } from 'react';
import { useQuery } from '@tanstack/react-query';
import { predictionService, patientService } from '../services/api';
import { useNavigate, useLocation } from 'react-router-dom';
import { Search, Loader2, FileText, ChevronRight, AlertCircle } from 'lucide-react';
import { formatConfidence } from '../utils/format';
import { cn } from '../utils/cn';
import { EmptyStateLung } from '../components/illustrations';

export default function PredictionsList() {
  const navigate = useNavigate();
  const location = useLocation();
  const [search, setSearch] = useState('');
  const [filterRisk, setFilterRisk] = useState('');

  const { data: predictions, isLoading, isError: predictionsError, refetch: refetchPredictions } = useQuery({
    queryKey: ['all-predictions'],
    queryFn: predictionService.getAll,
    retry: (failureCount, error) => error?.response?.status !== 401,
  });

  const { data: patients, isError: patientsError, refetch: refetchPatients } = useQuery({
    queryKey: ['patients'],
    queryFn: patientService.getAll,
    retry: (failureCount, error) => error?.response?.status !== 401,
  });

  const patientMap = useMemo(() => {
    if (!patients?.length) return {};
    const m = {};
    patients.forEach((p) => { m[p.id] = p.name; });
    return m;
  }, [patients]);

  const filtered = useMemo(() => {
    if (!predictions?.length) return [];
    let list = predictions;
    if (search.trim()) {
      const q = search.toLowerCase();
      list = list.filter(
        (p) =>
          (p.final_diagnosis && p.final_diagnosis.toLowerCase().includes(q)) ||
          (patientMap[p.patient_id] && patientMap[p.patient_id].toLowerCase().includes(q)) ||
          String(p.id).includes(q)
      );
    }
    if (filterRisk) {
      list = list.filter((p) => (p.urgency_level || '').toLowerCase() === filterRisk.toLowerCase());
    }
    return list.sort((a, b) => new Date(b.created_at) - new Date(a.created_at));
  }, [predictions, search, filterRisk, patientMap]);

  const isReportsPage = location.pathname === '/reports';

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-white">
          {isReportsPage ? 'Reports' : 'AI Predictions'}
        </h1>
        <p className="text-slate-400 mt-1">
          {isReportsPage
            ? 'Search and filter diagnostic reports.'
            : 'All predictions generated by the AI model.'}
        </p>
      </div>

      <div className="flex flex-col sm:flex-row gap-4">
        <div className="relative flex-1">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-slate-400" />
          <input
            type="search"
            placeholder="Search by diagnosis or patient name..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="w-full pl-10 pr-4 py-2.5 border border-slate-600 rounded-lg bg-slate-800/60 text-slate-200 placeholder-slate-500 text-sm focus:ring-2 focus:ring-sky-500/30"
          />
        </div>
        <select
          value={filterRisk}
          onChange={(e) => setFilterRisk(e.target.value)}
          className="px-4 py-2.5 border border-slate-600 rounded-lg bg-slate-800/60 text-slate-200 text-sm"
        >
          <option value="">All risk levels</option>
          <option value="low">Low</option>
          <option value="medium">Medium</option>
          <option value="high">High</option>
        </select>
      </div>

      {predictionsError || patientsError ? (
        <div className="flex flex-col items-center justify-center py-24 text-center">
          <AlertCircle className="w-12 h-12 text-red-400" />
          <h2 className="mt-4 text-lg font-semibold text-white">Failed to load reports</h2>
          <p className="mt-2 text-sm text-slate-400 max-w-sm">Check the browser console for API errors.</p>
          <button
            type="button"
            onClick={() => { refetchPredictions(); refetchPatients(); }}
            className="mt-4 px-4 py-2 bg-sky-500 text-white rounded-xl text-sm font-medium hover:bg-sky-400"
          >
            Retry
          </button>
        </div>
      ) : isLoading ? (
        <div className="flex items-center justify-center py-24">
          <Loader2 className="w-10 h-10 text-sky-400 animate-spin" />
        </div>
      ) : !filtered.length ? (
        <div className="glass-card border border-slate-700/50 rounded-xl py-16 text-center">
          <EmptyStateLung className="w-28 h-22 mx-auto text-sky-500/50" />
          <p className="mt-4 text-slate-400">No reports found.</p>
          <p className="mt-1 text-xs text-slate-500">Upload a scan to generate AI predictions.</p>
          <button
            type="button"
            onClick={() => navigate('/upload')}
            className="mt-4 px-4 py-2 bg-sky-500/20 border border-sky-500/40 text-sky-300 rounded-xl text-sm font-medium hover:bg-sky-500/30"
          >
            Upload scan
          </button>
          <button
            type="button"
            onClick={() => navigate('/dashboard')}
            className="mt-3 ml-2 px-4 py-2 text-sky-400 font-medium text-sm hover:text-sky-300"
          >
            Back to dashboard
          </button>
        </div>
      ) : (
        <div className="glass-card border border-slate-700/50 rounded-xl overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full text-left">
              <thead>
                <tr className="border-b border-slate-700/50 bg-slate-800/30">
                  <th className="px-6 py-3 text-xs font-semibold text-slate-400 uppercase tracking-wider">Report ID</th>
                  <th className="px-6 py-3 text-xs font-semibold text-slate-400 uppercase tracking-wider">Patient</th>
                  <th className="px-6 py-3 text-xs font-semibold text-slate-400 uppercase tracking-wider">Diagnosis</th>
                  <th className="px-6 py-3 text-xs font-semibold text-slate-400 uppercase tracking-wider">Confidence</th>
                  <th className="px-6 py-3 text-xs font-semibold text-slate-400 uppercase tracking-wider">Risk</th>
                  <th className="px-6 py-3 text-xs font-semibold text-slate-400 uppercase tracking-wider">Date</th>
                  <th className="px-6 py-3 w-10" />
                </tr>
              </thead>
              <tbody>
                {filtered.map((row) => (
                  <tr
                    key={row.id}
                    onClick={() => navigate(`/predictions/${row.id}`)}
                    className="border-b border-slate-800/50 hover:bg-slate-800/40 cursor-pointer transition-colors"
                  >
                    <td className="px-6 py-4 text-sm text-slate-400">#{row.id}</td>
                    <td className="px-6 py-4 text-sm font-medium text-white">
                      {patientMap[row.patient_id] ?? `Patient #${row.patient_id}`}
                    </td>
                    <td className="px-6 py-4 text-sm font-medium text-white">{row.final_diagnosis ?? '—'}</td>
                    <td className="px-6 py-4 text-sm text-sky-300 tabular-nums">{formatConfidence(row.confidence)}</td>
                    <td className="px-6 py-4">
                      <span
                        className={cn(
                          "inline-block px-2 py-1 rounded text-xs font-medium",
                          row.urgency_level === 'High' && "bg-red-500/20 text-red-400",
                          row.urgency_level === 'Medium' && "bg-amber-500/20 text-amber-400",
                          (row.urgency_level === 'Low' || !row.urgency_level) && "bg-emerald-500/20 text-emerald-400"
                        )}
                      >
                        {row.urgency_level ?? '—'}
                      </span>
                    </td>
                    <td className="px-6 py-4 text-sm text-slate-500">{new Date(row.created_at).toLocaleDateString()}</td>
                    <td className="px-6 py-4">
                      <ChevronRight className="w-4 h-4 text-slate-500" />
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}
    </div>
  );
}
